#
# Platform independent Docker compose configuration that syncs out a git branch
# (master is default) and/or a tag, and produced distribution installers for it.
# This is equivalent to ./gradlew install, or ./gradlew :xdk:dist<Archive>, where
# <Archive> is "Tar", "Zip" or "Exe". In the last case, we will build a native
# Windows executable installer. (This is done by a hard coded extra container
# from image 'nsis' that shares the build volume with the container from image
# 'xdk'
#
# We also create a separate docker volume for the Gradle cache/GRADLE_USER_HOME,
# to be able to repeatedly build faster, and only build what is necessary, should
# we change the input source tree.
#

#
# Set up shared volumes for the repository clome/build directory from GitHub
# and for the Gradle cache.
#
volumes:
  src:
  cache:

#
# Set up secrets from the default locations, so that we can do things like
# publications, artifact signing or other Gradle operations, where sensitive
# information is stored outside the repository.
#
secrets:
  gradle_properties:
    external: true
    file: $HOME/gradle/gradle.properties

services:
  xdk:
    image: ghcr.io/xtclang/xdk-builder
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.xdk
      args:     
        DOCKER_BUILDKIT: 1
        BASE_IMAGE: gradle:8.5.0-jdk21
        GITHUB_BRANCH: ${GITHUB_BRANCH:-master}
    environment:
      GRADLE_TASK: ${GRADLE_TASK:-install}
      GRADLE_LOG_LEVEL_FLAG: --info
    network_mode: host
    volumes:
      - src:/home/gradle/xvm
      - cache:/home/gradle/.gradle
      - type: bind
        source: ./build
        target: /build
    command: /bin/bash
#    secrets:
#      - gradle_properties
